version: '3.3'

services:
  github:
    build:
      context: ./GithubMicroservice
      dockerfile: Dockerfile
    container_name: "github"
    ports:
      - "8081:8080"

  twitter:
    build:
      context: ./TwitterMicroservice
      dockerfile: Dockerfile
    container_name: "twitter"
    ports:
      - "8082:8080"

  agregator:
    build:
      context: ./Agregator
      dockerfile: Dockerfile
    container_name: "agregator"
    depends_on:
      - github
      - twitter

    ports:
      - "8080:8080"
